<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Catalog\Block\Product\View */ ?>


<?php

$_product = $block->getProduct();
$_price = $_product->getPrice();
$finalPrice = $_product->getFinalPrice();

?>
<?php if ($priceAmount = $_product->getFinalPrice()):?>
    <div class="no-display price product-price"><?php echo $priceAmount; ?></div>
<?php endif;?>

<div class="preco">
    O parcelamento entra aqui...
    <?php echo $block->getChildHtml('product.info.price') ?>
    <div class="parcelamento">
        <span class="price_highlight">R$ <?php echo number_format($finalPrice-$finalPrice*0.1, 2, ',', ''); ?></span> a vista no boleto <span class="ic fa fa-barcode"></span>
        <br> ou em até <span class="price_highlight">6 x R$<?php echo number_format($finalPrice/6, 2, ',', ''); ?></span> sem juros
    </div>
    <div class="clearfix"></div>
</div>